language: python

python:
  - "2.7"

git:
  depth: 10

services:
  - docker

install:
  - pip install --upgrade pip setuptools wheel
  - pip install pandas,numpy,matplotlib

script:
  - (cd testing && make test_all)
