language: python

python:
  - "2.7"

git:
  depth: 10

notifications:
  email: false

services:
  - docker

before_install:
  - docker pull michaelwetter/ubuntu-1604_jmodelica_trunk

install:
  - pip install --upgrade pip
  - pip install pandas numpy matplotlib requests
  - mkdir $HOME/git && mkdir $HOME/git/ibpsa && mkdir $HOME/git/buildings
  - cd $HOME/git/ibpsa && git clone https://github.com/ibpsa/modelica-ibpsa.git
  - cd $HOME/git/buildings && git clone https://github.com/lbl-srg/modelica-buildings.git

before_script:
  - chmod +x $HOME/git/buildings/modelica-buildings/Buildings/Resources/Scripts/travis/bin/jm_ipython.sh
  - cp $HOME/git/buildings/modelica-buildings/Buildings/Resources/Scripts/travis/bin/jm_ipython.sh $HOME/bin/
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export MODELICAPATH=$HOME/git/ibpsa/modelica-ibpsa:$HOME/git/buildings/modelica-buildings
  
script:
  - (export TEST_ENV=travis && cd testing && make test_all)

