language: python

git:
  depth: 10

notifications:
  email: false

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.0
  jobs:
    - TEST=test_parser
    - TEST=test_data
    - TEST=test_forecast
    - TEST=test_kpis
    - TEST=test_readme_commands
    - TEST=test_testcase1
    - TEST=test_testcase2
    - TEST=test_testcase3
    - TEST=test_bestest_air
    - TEST=test_bestest_hydronic
    - TEST=test_bestest_hydronic_heat_pump
    - TEST=test_multizone_residential_hydronic
    - TEST=test_singlezone_commercial_hydronic
    - TEST=test_multizone_office_simple_air

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

jobs:
  include:
  - python: 3.9
    install: pip install --upgrade pip && pip install pandas==1.2.5 numpy==1.20.2 matplotlib==3.3.4 requests==2.25.1
    script: cd testing && make build_jm_image && make build_boptest_image && make $TEST
  - python: 2.7
    install: pip install --upgrade pip && pip install pandas==0.24.2 numpy==1.16.6 matplotlib==2.1.1 requests==2.18.4
    script: cd testing && make test_python2
